{% set version = "3.1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rotl
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rotl_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rotl/rotl_{{ version }}.tar.gz
  sha256: 12baeef897c835d20a4d84cf058a3d3d09b89202f7ec0325140cb7754ab5635c

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ape
    - r-assertthat >=0.1
    - r-httr
    - r-jsonlite
    - r-rentrez
    - r-rncl >=0.6.0
  run:
    - r-base
    - r-ape
    - r-assertthat >=0.1
    - r-httr
    - r-jsonlite
    - r-rentrez
    - r-rncl >=0.6.0

test:
  commands:
    - $R -e "library('rotl')"           # [not win]
    - "\"%R%\" -e \"library('rotl')\""  # [win]

about:
  home: https://github.com/ropensci/rotl
  license: BSD-2-Clause
  summary: An interface to the 'Open Tree of Life' API to retrieve phylogenetic trees, information about studies used to assemble the synthetic tree, and utilities to match taxonomic names to 'Open Tree identifiers'. The 'Open Tree of Life' aims at assembling a comprehensive phylogenetic tree for all named species.
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_2_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: rotl
# Title: Interface to the 'Open Tree of Life' API
# Version: 3.0.9
# Authors@R: c( person("Francois", "Michonneau", role=c("aut", "cre"), email="francois.michonneau@gmail.com", comment = c("ORCID" = "0000-0002-9092-966X")), person("Joseph", "Brown", role="aut", comment = c("ORCID" = "0000-0002-3835-8062")), person("David", "Winter", role="aut", comment = c("ORCID" = "0000-0002-6165-0029")), person("Scott", "Chamberlain", role="rev", comment = c("ORCID" = "0000-0003-1444-9135")))
# Description: An interface to the 'Open Tree of Life' API to retrieve phylogenetic trees, information about studies used to assemble the synthetic tree, and utilities to match taxonomic names to 'Open Tree identifiers'. The 'Open Tree of Life' aims at assembling a comprehensive phylogenetic tree for all named species.
# URL: https://github.com/ropensci/rotl
# BugReports: https://github.com/ropensci/rotl/issues
# Depends: R (>= 3.1.1)
# Imports: httr, jsonlite, assertthat (>= 0.1), rncl (>= 0.6.0), ape, rentrez
# License: BSD_2_clause + file LICENSE
# Suggests: knitr (>= 1.12), rmarkdown (>= 0.7), testthat, RNeXML, phylobase, MCMCglmm, fulltext (>= 0.1.6), readxl
# VignetteBuilder: knitr
# LazyData: true
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# X-schema.org-keywords: metadata, ropensci, phylogenetics, independant-contrasts, biodiversity
# X-schema.org-isPartOf: https://ropensci.org
# X-schema.org-relatedLink: https://codemeta.github.io/codemetar
# NeedsCompilation: no
# Packaged: 2019-06-14 14:33:36 UTC; francois
# Author: Francois Michonneau [aut, cre] (<https://orcid.org/0000-0002-9092-966X>), Joseph Brown [aut] (<https://orcid.org/0000-0002-3835-8062>), David Winter [aut] (<https://orcid.org/0000-0002-6165-0029>), Scott Chamberlain [rev] (<https://orcid.org/0000-0003-1444-9135>)
# Maintainer: Francois Michonneau <francois.michonneau@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-06-14 15:50:05 UTC
