{% set version = "3.0.6" %}

package:
  name: r-rotl
  version: {{ version }}

source:
  fn: rotl_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rotl_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rotl/rotl_{{ version }}.tar.gz
  sha256: f2716828c45c2680af025ca827491e1e9067b893979d4952f8e12a8d20279ca5

build:
  noarch: generic
  number: 0
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-httr
    - r-jsonlite
    - r-assertthat >=0.1
    - r-rncl >=0.6.0
    - r-ape
    - r-rentrez
    - r-xml
  run:
    - r-base
    - r-httr
    - r-jsonlite
    - r-assertthat >=0.1
    - r-rncl >=0.6.0
    - r-ape
    - r-rentrez
    - r-xml

test:
  commands:
    - $R -e "library('rotl')"  # [not win]
    - "\"%R%\" -e \"library('rotl')\""  # [win]

about:
  home: https://cran.r-project.org/package=rotl
  license: BSD 2 Clause
  license_file: LICENSE
  summary: An interface to the 'Open Tree of Life' API to retrieve phylogenetic trees, information
    about studies used to assemble the synthetic tree, and utilities to match taxonomic
    names to 'Open Tree identifiers'. The 'Open Tree of Life' aims at assembling a comprehensive
    phylogenetic tree for all named species.

extra:
  recipe-maintainers:
    - ocefpaf
